---
title: "Test-Plotting"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggforce)
```

```{r}
draw_circles <- function(graph, new_t_indx) {
  for(i in 1:6) {
     graph <- graph + annotate("path",
     x=coordinates[i,1]+distances[i,new_t_indx]*cos(seq(0,2*pi,length.out=100)),
     y=coordinates[i,2]+distances[i,new_t_indx]*sin(seq(0,2*pi,length.out=100)))
  }
  graph
  x
  y
}
```

```{r}
strs <- c("Hello dear", "Hi dear", "How was your day dear", "My day was good", "How was your class", "It was good how was yours")
similar_words <- c(2, 1, 1, 0, 0, 0, 
                   1, 2, 1, 0, 0, 0, 
                   1, 1, 5, 2, 3, 1, 
                   0, 0, 2, 4, 1, 2, 
                   0, 0, 3, 1, 4, 0, 
                   0, 0, 3, 2, 0, 6)
similar_words = matrix(similar_words, nrow=6, ncol=6)

max_lengths <- c(2, 2, 5, 4, 4, 6, 
                 2, 2, 5, 4, 4, 6, 
                 5, 5, 5, 5, 5, 6, 
                 4, 4, 5, 4, 4, 6,
                 4, 4, 5, 4, 4, 6, 
                 6, 6, 6, 6, 6, 6)
max_lengths <- matrix(max_lengths, nrow=6, ncol=6)

distances <- 1000* (1 - (similar_words / max_lengths))
distances <- matrix(distances, nrow=6, ncol=6)
distances

coordinates <- matrix(nrow=6, ncol=2)
coordinates[1,1] = 0
coordinates[1, 2] = 0
coordinates[2,1] =  0
coordinates[2, 2] = distances[2,1]

coordinates = data.frame(coordinates)
```

```{r}
graph <- ggplot(data=coordinates, aes(x=coordinates[,1], y=coordinates[,2])) + geom_point()
draw_circles(graph, 2)

coordinates[3,2] <- .25

```

```{r}
#Graph for positive .75
coordinates[3,1] <- .75
graph <- ggplot(data=coordinates, aes(x=coordinates[,1], y=coordinates[,2])) + geom_point()
draw_circles(graph, 4)
?prcomp
```

```{r}
#Graph for negitive .75
coordinates[3,1] <- -.75
graph <- ggplot(data=coordinates, aes(x=coordinates[,1], y=coordinates[,2])) + geom_point()
draw_circles(graph, 4)
```
```{r}
?princomp
fit <- princomp(distances)
summary(fit)
loadings(fit)
plot(fit, type='lines')
fit$scores
biplot(fit)
?biplot
distances
```



